### ISSUE TITLE
its not working i added into my project.previuously it worked . i checked where was wrong but i didn't found anything else 

### ISSUE THREAD

**Issue by YERUVAKONIREDDY** [dipkasyap/DGLocalization#2]
its not working i added into my project.previuously it worked . i checked where was wrong but i didn't found anything else

**Comment by dipkasyap** [comment]
Can you provide detail of your project, Xcode version, swift version etc?

**Comment by dipkasyap** [comment]
I am closing this issue, as no response from the user.
